version: '3'

services:
  db:
    image: mariadb:10.11
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: PASSWD
      MYSQL_PASSWORD: PASSWD
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  app:
    build: .
    restart: always
    environment:
      MYSQL_PASSWORD: PASSWD
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    volumes:
      - nextcloud:/var/www/html
      - /mnt/pool/smb:/mnt/pool_smb
      - /FHFshare/smb:/mnt/fhf_smb
    expose:
      - 80   # expose internal port 80 to other containers, no host mapping

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "443:443"   # HTTPS port
      - "80:80"     # optional: HTTP redirect to HTTPS or for Let's Encrypt challenge
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/certs/nextcloud.crt:/etc/nginx/ssl/nextcloud.crt:ro
      - /etc/ssl/private/nextcloud.key:/etc/nginx/ssl/nextcloud.key:ro
    depends_on:
      - app

volumes:
  db:
  nextcloud:
